/*
 * SPDX-FileCopyrightText: 2024 Roland Rusch, easy-smart solution GmbH <roland.rusch@easy-smart.ch>
 * SPDX-License-Identifier: BSD-3-Clause
 */


#define LIBSMART_STM32NETX_DEFAULT_MEMORY_SIZE 1024

#define LIBSMART_STM32NETX_NETX_THREAD_STACK_SIZE (2*LIBSMART_STM32NETX_DEFAULT_MEMORY_SIZE)

#define LIBSMART_STM32NETX_NETX_LINK_CHECK_INTERVAL (3 * TX_TIMER_TICKS_PER_SECOND)
#define LIBSMART_STM32NETX_NETX_DHCP_WAIT_TIME (6 * TX_TIMER_TICKS_PER_SECOND)

#define LIBSMART_STM32NETX_PAYLOAD_SIZE ETH_RX_BUF_SIZE

#define LIBSMART_STM32NETX_PACKET_POOL_SIZE ((LIBSMART_STM32NETX_PAYLOAD_SIZE + sizeof(NX_PACKET)) * 10)


#define LIBSMART_STM32NETX_ENABLE_DHCP
// #undef LIBSMART_STM32NETX_ENABLE_DHCP
